// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeedammryEPi4tZuZ2-sLSQziRgQRnu0M',
    appId: '1:641864841613:web:5225cf1c0074d9334065c4',
    messagingSenderId: '641864841613',
    projectId: 'performance-monitoring-44f1e',
    authDomain: 'performance-monitoring-44f1e.firebaseapp.com',
    storageBucket: 'performance-monitoring-44f1e.firebasestorage.app',
    measurementId: 'G-3BET7031KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQANoR3lFTY2g6ud4xYUzG2iSfhfMGL1U',
    appId: '1:641864841613:android:0c266a7d653c2d554065c4',
    messagingSenderId: '641864841613',
    projectId: 'performance-monitoring-44f1e',
    storageBucket: 'performance-monitoring-44f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3mot0DUODVCGydGNHYTym9FcKCj-3zQ',
    appId: '1:641864841613:ios:97cd6763806d17024065c4',
    messagingSenderId: '641864841613',
    projectId: 'performance-monitoring-44f1e',
    storageBucket: 'performance-monitoring-44f1e.firebasestorage.app',
    iosBundleId: 'com.example.operationcore2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ3mot0DUODVCGydGNHYTym9FcKCj-3zQ',
    appId: '1:641864841613:ios:97cd6763806d17024065c4',
    messagingSenderId: '641864841613',
    projectId: 'performance-monitoring-44f1e',
    storageBucket: 'performance-monitoring-44f1e.firebasestorage.app',
    iosBundleId: 'com.example.operationcore2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeedammryEPi4tZuZ2-sLSQziRgQRnu0M',
    appId: '1:641864841613:web:5c3bf52bea9b5af74065c4',
    messagingSenderId: '641864841613',
    projectId: 'performance-monitoring-44f1e',
    authDomain: 'performance-monitoring-44f1e.firebaseapp.com',
    storageBucket: 'performance-monitoring-44f1e.firebasestorage.app',
    measurementId: 'G-X5FSXNWZ9Z',
  );
}
